//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMGAPP.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FMGEntities : DbContext
    {
        public FMGEntities()
            : base("name=FMGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EXPENDITURE> EXPENDITUREs { get; set; }
        public virtual DbSet<EXPENDITURE_TITLE> EXPENDITURE_TITLE { get; set; }
        public virtual DbSet<IMAGE_DOCUMENT> IMAGE_DOCUMENT { get; set; }
        public virtual DbSet<LOGIN> LOGINs { get; set; }
        public virtual DbSet<MONTH> MONTHs { get; set; }
        public virtual DbSet<OFFERING> OFFERINGs { get; set; }
        public virtual DbSet<OFFERING_STATUS> OFFERING_STATUS { get; set; }
        public virtual DbSet<TEXT_DOCUMENT> TEXT_DOCUMENT { get; set; }
    }
}
