//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMGAPP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFERING_STATUS
    {
        public int offeringStatusID { get; set; }
        public string offeringStatus { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
    }
}
