//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMGAPP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEXT_DOCUMENT
    {
        public int documentTextID { get; set; }
        public string documentName { get; set; }
        public string documentType { get; set; }
        public string documentPath { get; set; }
        public int day { get; set; }
        public int monthID { get; set; }
        public int year { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
    }
}
